version: '2'

services:
  app: &app
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/app/
      - bundler_gems:/usr/local/bundle/
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - bigtable

  bigtable:
    build:
      context: .
      dockerfile: Dockerfile.bigtable
    env_file: .env
    ports:
      - '8086:8086' # Bigtable
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086

volumes:
  bundler_gems:
  node_modules: